//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kevin.Permission.Domain.Entity.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kevin.Permission.Domain.Entity.Resource.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 该角色无法继承给定的继承的角色,给定的继承角色与该角色已存在继承关系 的本地化字符串。
        /// </summary>
        internal static string exception_CycleInherit {
            get {
                return ResourceManager.GetString("exception_CycleInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该类型的角色不允许继承 的本地化字符串。
        /// </summary>
        internal static string exception_NotEnableInherit {
            get {
                return ResourceManager.GetString("exception_NotEnableInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色未继承给定的继承的角色 的本地化字符串。
        /// </summary>
        internal static string exception_NotInheritTheRole {
            get {
                return ResourceManager.GetString("exception_NotInheritTheRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继承的角色的类型和当前角色的类型必须一样 的本地化字符串。
        /// </summary>
        internal static string exception_RoleCateogyShouldSame {
            get {
                return ResourceManager.GetString("exception_RoleCateogyShouldSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色已经继承某角色,该类型的角色只能继承一个角色 的本地化字符串。
        /// </summary>
        internal static string exception_RoleShouldSingleInherit {
            get {
                return ResourceManager.GetString("exception_RoleShouldSingleInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色不能继承角色本身 的本地化字符串。
        /// </summary>
        internal static string exception_ShouldNotSelfInherit {
            get {
                return ResourceManager.GetString("exception_ShouldNotSelfInherit", resourceCulture);
            }
        }
    }
}
